### ISSUE TITLE
Attribute configured? testcase to address attribute

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AdministratorAdministration#113]
In address attribute, either one of ipv-4-address or domain-name should be present. If the request contains ipv-4-address, in the target tcp-client instance, already available attribute should be replaced with ipv-4-address. Vice versa is expected for domain-name

This behavior can be tested by following:

Retrieve and store actual tcp instance and its necessary dependent instances.
If the available address attribute is ip-address/ipv-4-address, we can post domain-name in request-body
Check if the attribute is updated in target instance and the ip-address attribute is removed.
Clearing with POST request with initial configurations for clearing and check if the instance is cleared as expected
Repeat the same if initially "domain-name" is present in tcp-instance with "ip-address" attribute in request body. Finally clear with domain-name
These steps need to be followed for the following services.
- [ ] /v1/bequeath-your-data-and-die
 - [ ] /v1/regard-application

**Comment by PrathibaJee** [comment]
Closing this issue , as it is invalid.
