### ISSUE TITLE
Include OAM services for the FILE_PROFILE to include database

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AdministratorAdministration#128]
Implement the logic in the controllers and services for the following services , 

- [ ] GET /core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-capability/file-identifier
- [ ] GET /core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-capability/file-description
- [ ] GET and PUT /core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-configuration/file-path
- [ ] GET and PUT/core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-configuration/user-name
- [ ] GET and PUT /core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-configuration/password
- [ ] GET and PUT /core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-configuration/operation

**Comment by ManasaBM1** [comment]
pull request created for this issue https://github.com/openBackhaul/AdministratorAdministration/pull/150
