### ISSUE TITLE
Support Version 2.0.0 changes for FileProfile

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AdministratorAdministration#129]
1. Generate server stub for the version 2.0.0 specification 
2. Copy the files controllers/IntegerProfile.js and service/FileProfile.js from the generated stub to the source code.
3. If the api/openapi.yaml is not updated as per the published version 2.0.0 , then copy the api/openapi.yaml file from the generated stub to the source code

Following tasks needs to be completed to support FileProfile in version 2.0.0
- [ ] https://github.com/openBackhaul/AdministratorAdministration/issues/128

**Comment by ManasaBM1** [comment]
pull request created for this issue https://github.com/openBackhaul/AdministratorAdministration/pull/150
