### ISSUE TITLE
Support Version 2.0.0 changes to remove AdminProfile

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AdministratorAdministration#132]
1. Generate server stub for the version 2.0.0 specification 
2. If the api/openapi.yaml is not updated as per the published version 2.0.0 , then copy the api/openapi.yaml file from the generated stub to the source code. This will not consists of the AdminProfile related specification.4. 
3. Remove the files controllers/AdminProfile.js and service/AdminProfile.js from the source code.

**Comment by ManasaBM1** [comment]
this issue is closed with Ap pull request
