### ISSUE TITLE
Support version 2.0.0 changes

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AdministratorAdministration#134]
To completely implement the version 2.0.0 changes , the following tasks and their subtasks needs to be completed.
All the tasks needs to be implemented , tested , reviewed and merged to the develop branch.

### Individual Services :
- [x] https://github.com/openBackhaul/AdministratorAdministration/issues/121
- [x] https://github.com/openBackhaul/AdministratorAdministration/issues/125
- [x] https://github.com/openBackhaul/AdministratorAdministration/issues/126
- [x] https://github.com/openBackhaul/AdministratorAdministration/issues/127
- [x] https://github.com/openBackhaul/AdministratorAdministration/issues/131
- [x] https://github.com/openBackhaul/AdministratorAdministration/issues/133

### Basic Services :
- [x] https://github.com/openBackhaul/AdministratorAdministration/issues/140

### OAM Services :
- [x] https://github.com/openBackhaul/AdministratorAdministration/issues/141
- [x] https://github.com/openBackhaul/AdministratorAdministration/issues/132

**Comment by DanaSunal** [comment]
All subtasks are done.
