### ISSUE TITLE
while executing Regard-application with port number same as where the server is running is not getting Updated correctly 

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/AdministratorAdministration#184]
while executing Regard-application with port number same as where the server is running is not getting Updated correctly . it is updateing with tcp-server port and ipaddress

**Comment by ManasaBM1** [comment]
currently not observing this issue so keep on hold and in the next testsuite run we will observe and close the issue

**Comment by PrathibaJee** [comment]
Closing this issue , as it is not reproducing in the latest environment.
