### ISSUE TITLE
application-data.json file needs to be created for test-suite run

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/AdministratorAdministration#204]
**Issue Description:** 
One of the test case scenario related to service /v1/approve-oam-request is we will send one of the methods in enum value that is not having proper authorization and check whethe proper response "METHOD_NOT_ALLOWED" is fetched or not.

But , the above scenario is failing as correct response of "METHOD_NOT_ALLOWED" is not fetched . 

**Root Cause:**
As , application-data.json present in docker container is having correct authorization code for method ALL which  means all methods present in the enum will have access.

**Solution  :** 
For test suite run , CI/CD team will be provided with temporary application-data.json file , such that ALL methods will not be allowed .

**Comment by PrathibaJee** [comment]
Handled this request(to include the testdata) in the CICD pipeline. Hence closing this issue.
