### ISSUE TITLE
when /V1/BEQUEATH-YOUR-DATA-AND-DIE service   forwarding is triggered then new OperationClinet ltp is creating in the newrelease 

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/AdministratorAdministration#220]
**Issue Description** : when we execute the /V1/BEQUEATH-YOUR-DATA-AND-DIE service then once forwardings got triggered It is creating a new Operation-Client ltp under the NewRelease for the "/v1/inquire-oam-request-approvals".

**Root cause**: In the  /V1/BEQUEATH-YOUR-DATA-AND-DIE service Since the isDatatansferisRequired is passing as  true in the softwareUpgrade.js  so it is calling the forwarding called  "PromptForBequeathingDataCausesTransferOfListOfApplications"
so it is sending a information to newRelease .

> Priority:High

**Comment by PrathibaJee** [comment]
Problem resolved as a part of the fix in the issue https://github.com/openBackhaul/ApplicationPattern/issues/736.
Hence closing this issue.
