### ISSUE TITLE
Update release-number of http-c to 2.0.1

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AdministratorAdministration#228]
Current scenario:
In load-file of applications, the http-c/release-number(s) of client applications are 1.0.0.

Problem statement:
Since, the services in v2.0.1 are not backward compatible with v1.0.0, while registering a v2.0.1 of an application, callbacks of /v1/bequeath-your-data-and-die gets failed during data transfer and subscription transfer phases. (because of difference in attribute names or presence of additional attributes).

Related issue : https://github.com/openBackhaul/ApplicationPattern/issues/713

**Comment by openBackhaul** [comment]
**Result of discussion during the June 16, 2023 Implementation Call:**
The 2.0.1 specification does not take backward compatibility restrictions into account.
As a result, the bequeath-your-data-and-die process cannot run properly.
It has been decided to treat 2.0.1 like an initial release (1.0.0) and reinstall the platform from scratch (so no update process).
Potential future **2.0.2 must respect backwards compatibility rules, and OldRelease must identify 2.0.1 as the ReleaseNumber in the ConfigFile.**

**Comment by openBackhaul** [comment]
OldRelease::ReleaseNumber is configured to be 2.0.1 in the CONFIGfile.
