### ISSUE TITLE
Request to restrict OldRelease and NewRelease instances while fetching for http-c of application

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/AdministratorAdministration#231]
**Problem Description :**

When a new release of existing application is Entering into the architecture, it will update the http-c , tcp-c of Old Release in config file of New Release with the preceding application information provided in request body of /v1/register-yourself.

Once the application is approved and receives “embed-yourself” , a callback will be triggered to the old application’s “/v1/bequeath-your-data-and-die” .

When /v1/bequeath-your-data-and-die is executed, as part of callback **PromptForBequeathingDataCausesTransferOfListOfApplications** it will transfer the client applications from old Release to New Release by calling regard-application in New Release .

As part of execution of regard-application , it will find whether applications exists or not , if it exists it will update the instance with current details .

During this process, if we are trying to regard preceding application client instance , it will find oldRelease client as preceding application instance instead of correct instance and it will update the details which is not expected.

**Proposal :**

In OAS , for services like _/v1/regard-application, /v1/disregard-application_ can we add description for application-name and release-number attributes like 
`" **update shall be made considering http-c instances excluding OldRelease and NewRelease http-c instances** " . `

_Note_ : In implementation, the OldRelease and NewRelease instances shall be considered from forwarding-constructs like PromptForEmbeddingCausesRequestForBequeathingData and PromptForBequeathingDataCausesTransferOfListOfApplications respectively. (The forwardings would vary based on application)

```
Example: 
 properties:
  application-name:
      description: 
         'Name of application that shall be requested for service request notifications
          find or create [/core-model-1-4:control-construct/logical-termination-point=aa-2-0-1-http-c-*/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]
          (update shall be made considering http-c instances excluding OldRelease and NewRelease http-c instances)'
    release-number:
       description: 
        'Release of application that shall be requested for service request notifications
          find or create [/core-model-1-4:control-construct/logical-termination-point=aa-2-0-1-http-c-*/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/release-number]
         (update shall be made considering http-c instances excluding OldRelease and NewRelease http-c instances )'
```

**Comment by vanithavalluripalli9** [comment]
As per decision made in https://github.com/openBackhaul/ExecutionAndTraceLog/issues/259 
**Change to be made at the OAS:**
_In /v1/regard-application and /v1/disregard-application the description has to be changed towards "update shall be made excluding OldRelease and NewRelease http-c instances" at application-name and release-number attributes ._

**Comment by openBackhaul** [comment]
Changed similar to proposal.
