### ISSUE TITLE
/v1/bequeath-your-data-and-die not transferring all the regarded application

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AdministratorAdministration#268]
To transfer the regarded application during /v1/bequeath-your-data-and-die , as per the load file , oldRelease have to transfer 8 applications to newRelease. 
But , as per the records in EATL , only 6 such records are there.
This issue is observed in the testsuite report, whereas manually it is working. 

>Priority:Medium;
>AffectedFlow:Software Upgrade/AA:/v1/bequeath-your-data-and-die;

**Comment by ManasaBM1** [comment]
Assertion failure details:
/v1/bequeath-your-data-and-die Forwardings triggered?:: BequeathingDataAndDieCausesForwardings:: Expected ExecutionAndTraceLog/v1/list-records-of-flow for /v1/bequeath-your-data-and-die
This issue observed in AA
