### ISSUE TITLE
Testexecution PostTermination mismatch in the initial and final configuration file

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/AdministratorAdministration#269]
Assertion failure details
In AA Software Upgrade  , following are the assertions that are failed because of this problem,

Provides expected properties in configuration class for 'aa-2-0-1-tcp-c-aa-2-0-1-000'

Reason :
In the test execution, the expectation is , the initial configuration file should match the final configuration.
But there is a mismatch. This mismatch are consequences of the failures of other assertions. Once the other assertion failures will be resolved , this shall also be cleared.

**Comment by PrathibaJee** [comment]
Since the v2.1.1 doesn't have test suite to validate the failure mentioned in the test execution we cannot validate and close this issue for now. So, moving this to the next release.

**Comment by PrathibaJee** [comment]
Since the v2.1.1 doesn't have test suite to validate the failure mentioned in the test execution we cannot validate and close this issue for now.
