### ISSUE TITLE
Request to Interchange the service-name of /v1/approve-basic-auth-request and /v1/approve-oam-request in OAS  

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/AdministratorAdministration#300]
**Issue Description:**
currently in the specification ,the details specified for the service  /v1/approve-basic-auth-request contains the details of service /v1/approve-oam-request
as mentioned below
 
/v1/approve-basic-auth-request
 
![MicrosoftTeams-image (1)](https://github.com/openBackhaul/AdministratorAdministration/assets/113175652/42f4cd08-9ca9-4bfc-8ec4-7f91dae1848e)

 
 
and similarly /v1/approve-oam-request contains the details of the service /v1/approve-basic-auth-request
 
![basicauthrequest](https://github.com/openBackhaul/AdministratorAdministration/assets/113175652/a9286f88-ff21-4dfe-ab54-1bc381233353)

 
**Solution:**
 
In the specification file , Interchange the the services names of /v1/approve-basic-auth-request and /v1/approve-oam-request

**Comment by PrathibaJee** [comment]
Issue covered in https://github.com/openBackhaul/AdministratorAdministration/issues/301
