### ISSUE TITLE
Changes required in the specification and Configuration file of 2.1.0

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AdministratorAdministration#301]
### To remove unused APIs in the bequeath-your-data-and-die callbacks
In /v1/bequeath-your-data-and-die , the following forwarding shall not be required,
1. PromptForBequeathingDataCausesRObeingRequestedToNotifyApprovalsOfNewApplicationsToNewRelease (as the same will be taken care by the embedding sequence)
2. PromptForBequeathingDataCausesRObeingRequestedToNotifyWithdrawnApprovalsToNewRelease (as the RO://v1/notify-withdrawn-approval is deprecated)
3. PromptForBequeathingDataCausesRObeingRequestedToStopNotificationsToOldRelease 

So , requesting the changes , 
**Specification :**
- [x] The above mentioned forwardings shall be deleted.

**Config file :**
- [x] The above mentioned forwarding shall be deleted.
- [x] Also , following operation-clients shall be removed as they will be not used , 
  aa-2-1-0-op-c-im-ro-2-1-0-000 /v1/notify-approvals
  aa-2-1-0-op-c-im-ro-2-1-0-001 /v1/notify-withdrawn-approvals
  aa-2-1-0-op-c-im-ro-2-1-0-002 /v1/end-subscription

--------

### To swap the path names of the API /v1/approve-basic-auth-request and /v1/approve-oam-request
In the specification , 
- the /v1/approve-basic-auth-request is marked as deprecated. And its operationId is approveOamRequest and it has the response/request body of /v1/approve-oam-request. 
- the /v1/approve-oam-request is not marked as deprecated. And its operationId is approveBasicAuthRequest and it has the response/request body of /v1/approve-basic-auth-request.

so , 
- [x] The path /v1/approve-basic-auth-request shall be replaced with /v1/approve-oam-request and vice versa.

--------
### To include the new APIs to few legacy forwardings

In the CONFIG file , the following operation-server shall be included as an input fc-port of the forwarding

- [x] **ServiceRequestCausesLoggingRequest,** 
aa-2-1-0-op-s-bm-013 - /v1/dispose-remainders-of-deregistered-application
aa-2-1-0-op-s-bm-014 - /v1/inform-about-preceding-release
aa-2-1-0-op-s-bm-015 - /v1/update-client-of-subsequent-release

- [x] **ServiceRequestCausesLtpUpdateRequest,**
aa-2-1-0-op-s-bm-015 - /v1/update-client-of-subsequent-release

- [x] **ServiceRequestCausesLtpDeletionRequest,**
aa-2-1-0-op-s-is-002 - /v1/disregard-application

**Comment by openBackhaul** [comment]
Changed as proposed.
