### ISSUE TITLE
Observation regarding AA server unavailability

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AdministratorAdministration#31]
When AA application goes down ,
**Impact :**
- OAM layer will be locked completely in all the applications.

**Note :**
- Once the application is back , operations will be resumed.
- The failure of this server can be identified either from the OL logs or by the response in the swagger UI.

### Proposal for High availability :
**Proposal#1 :** If we are planning to continue with docker engine , a simple shell script that 
- monitors the pid of the application’s port
- starts the container if the pid is not available
(already we have such scripts for other applications like traffic checker. Monitoring dashboard)

**Proposal#2 :** If we are planning to move to an orchestrator(docker swarm, Kubernetes) then the orchestrator will take care of it.

**Comment by PrathibaJee** [comment]
Please refer the [comment](https://github.com/openBackhaul/ExecutionAndTraceLog/issues/35#issuecomment-1172092260) to get a view about the discussion for a similar topic in the EATL repository.

Currently CICD engineer included a High Availability script that monitors the PID of the containers and brings it back whenever it goes to unavailability. High level information about this script is available in this [document ](https://github.com/openBackhaul/ApplicationPattern/blob/61ecdca2f3b36c1d82e7075e1ae764c499236eb3/doc/TestingApplications/TestingApplications.md#hascripts).

Further keeping this issue open under milestone v2.0.0_impl to observe the applications availability in the version 2.0.0 implementation.

**Comment by PrathibaJee** [comment]
@ManasaBM1 , Please close this issue if HA script is working as expected. Thanks.

**Comment by ManasaBM1** [comment]
HA script is working as expected , hence closing this issue
