### ISSUE TITLE
operations shall be updated to /v1/approve-basic-auth-request for RequestForInquiringOamApprovals and CreateLinkForApprovingOamRequests

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AdministratorAdministration#369]
In service, /v1/regard-application, we have callbacks _RegardApplicationCausesSequenceForInquiringOamRequestApprovals.RequestForInquiringOamApprovals_ and _RegardApplicationCausesSequenceForInquiringOamRequestApprovals.CreateLinkForApprovingOamRequests_. In which the attribute "_oam-approval-operation_" for former and "_operation-name_" for later is specified to point to _aa-2-1-0-op-s-is-004 (/v1/approve-oam-request)_ . 

As per example of that callback and as per the diagram (https://github.com/openBackhaul/AdministratorAdministration/blob/v2.1.1_spec/spec/diagrams/is002_regardApplicationCausesOamSequence.plantuml : line 66) , it shall be pointing to "_aa-2-1-0-op-s-is-005_" (/v1/approve-basic-auth-request).

**Comment by openBackhaul** [comment]
Uuids have been corrected as proposed.
