### ISSUE TITLE
Need suggestion on the value of release-number in application-data file

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AdministratorAdministration#370]
In application-data file, we have the attribute "_release-number_" which shall supposed to contain the actual release-number of the authorizable application. 

Kindly let us know for which of the following method shall be followed for the "_release-number_" attribute:
1. The release-number shall contain the actual release-number of the application. And when more than one release of same application is available, that shall be given as a separate instance under list of "allowed-access". 
   - This shall require the CICD engineer to edit the application-data file frequently during application upgrade. 
   - Example: During application upgrade, the application-data file shall included with new-release's data. Once upgrade is successful, the file shall be removed for the old-release's data. 
3. The release-number attribute is allowed to have "*" . 
    - By following this method, the application-data file shall not be updated frequently. 
    - This will allow a seem-less upgrade process for the application and will reduce authorization failure due to man-made mistake.  

Note: This question was raised during upgrading of an application, where under this scenario, two instance of a single application shall be available and that shall be authorized.

**Comment by openBackhaul** [comment]
ReleaseNumber shall no longer be checked against the DataFile.
Descriptions have been updated accordingly.
