### ISSUE TITLE
To support the 2.1.2 schema changes to the server side implementation

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AdministratorAdministration#375]
- [x] Generate server stub for the version 2.1.0 specification. Replace the server/api/openapi.yaml with the generated api/openapi.yaml file.
- [x] Replace the database/load.json file with the latest develop/spec/Administratoradministration+config.json file
- [x] Compare the controller and the services folder in the generated server side stub with the existing code. Update the existing code
- [x] serverPort shall be updated in index.js
- [x] port shall be updated for "EXPOSE" in dockerfile
- [x] version shall be updated to 2.1.2 in package.json
- [x] package-lock.json to be updated with new AP package

Reference for port : https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/TestingApplications/Infrastructure/SdnLaboratory/FakeAddresses/IpAddresses.md

**Comment by ManasaBM1** [comment]
Close this issue , raised PR
