### ISSUE TITLE
operation-name "inquire-basic-auth-approvals" shall be referenced from string profile instead of hardcoding

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AdministratorAdministration#377]
A string profile _aa-2-1-2-string-p-001_ has been introduced to AA. 

The "string-value" configured in this string-profile shall been considered as reference 
- to create operation-client instance during /v1/regard-application,
- while selecting the operation-client instances during callbacks

instead of hardcoding them.

**Comment by ManasaBM1** [comment]
Close this issue , raised PR
