### ISSUE TITLE
/v1/approve-basic-auth-request shall be used as operation-name for RequestForInquiringOamApprovals and CreateLinkForApprovingOamRequests callbacks

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AdministratorAdministration#378]
/v1/regard-application has multiple callbacks out of which RequestForInquiringOamApprovals and CreateLinkForApprovingOamRequests callbacks shall be updated with following. 

- [x] RequestForInquiringOamApprovals - oam-approval-operation shall be taken from **aa-2-1-2-op-s-is-005** which is /v1/approve-basic-auth-request
- [x] CreateLinkForApprovingOamRequests  - operation-name shall be taken from **aa-2-1-2-op-s-is-005** which is /v1/approve-basic-auth-request

instead of aa-2-1-2-op-s-is-004 which is /v1/approve-oam-request. because /v1/approve-basic-auth-request is backward compatible.

Ref: https://github.com/openBackhaul/AdministratorAdministration/issues/369

**Comment by ManasaBM1** [comment]
Close this issue , raised PR
