### ISSUE TITLE
/v1/approve-oam-request logic shall be updated

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AdministratorAdministration#379]
when a request is incoming for authorization to /v1/approve-oam-request, the following changes shall happen
- [x] **application-name** : shall be validated both in config file and application-data.json file
- [ ] **release-number** : shall be validated only in config file but could be ignored validation in application-data.json file.

**Comment by ManasaBM1** [comment]
Close this issue , raised PR
