### ISSUE TITLE
release-number attribute in application-data.json file shall be removed

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AdministratorAdministration#380]
As per decision made in https://github.com/openBackhaul/AdministratorAdministration/issues/370#issuecomment-2301662259, 

the release-number attribute shall be removed from application-data.json file.

(Further validations shall only happen against application-name, Auth code, operation-name and method)

**Comment by ManasaBM1** [comment]
Close this issue , raised PR
