### ISSUE TITLE
/v1/approve-basic-auth-request logic shall be updated

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AdministratorAdministration#381]
when a request is incoming for authorization to /v1/approve-basic-auth-request, the following changes shall happen for both the schemas.

- [x] **application-name** : shall be validated both in config file and application-data.json file
- [x] **release-number** : shall be validated only in config file but could be ignored validation in application-data.json file. 
- [x] **response-body** shall be updated based on conditions in updated specification

**Comment by ManasaBM1** [comment]
Close this issue , raised PR
