### ISSUE TITLE
OAMLayer : string profile shall be supported

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AdministratorAdministration#382]
In OamLayer, implementation of string-profile shall be included in Controllers and Service folders and shall be tested for proper working

- [x] getStringProfileStringName
- [x] getStringProfileEnumeration
- [x] getStringProfilePattern
- [x] getStringProfileStringValue
- [x] putStringProfileStringValue
- [x] Also, it shall be noted that, when PUT string-value is made, the request body shall be validated against the pattern defined in capability/pattern

**Comment by ManasaBM1** [comment]
Close this issue , raised PR
