### ISSUE TITLE
To mask basic authcode while documenting the records to EATL 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AdministratorAdministration#384]
This is specific to AccessAdministration, the following change shall be made for /v1/approve-oam-request and /v1/approve-basic-auth-request (for both schema)

- While req.body is being sent to executionAndTraceService.recordServiceRequest(), the attribute "**Authorization**" in request body shall be removed. Since it is sensitive information, it shall not be stored in ExecutionAndTraceLog

**Comment by ManasaBM1** [comment]
Close this issue , raised PR
