### ISSUE TITLE
Load file : detailed-logging-is-on attribute to be removed from logical-termination-point instances

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AdministratorAdministration#40]
As per understanding, detailed-logging-is-on attribute is applicable only for the operation "/v1/record-service-request" of ExecutionAndTraceLog

Problem Description:
In load-file, [AdministratorAdministration_0.0.2_tsi.211217.1845%2Bdata.2.json](https://github.com/openBackhaul/AdministratorAdministration/blob/develop/AdministratorAdministration_0.0.2_tsi.211217.1845%2Bdata.2.json),  for ltp instance aa-0-0-1-op-c-2040  contains an additional attribute _detailed-logging-is-on_, which needs to be removed.
Also an update needed in database/load-file of server 

Note : 
- aa-0-0-1-op-c-2040 refers to  /v1/inquire-oam-request-approvals

Related issues:
https://github.com/openBackhaul/ApplicationLayerTopology/issues/63
https://github.com/openBackhaul/OperationKeyManagement/issues/32
https://github.com/openBackhaul/OamLog/issues/41
https://github.com/openBackhaul/ExecutionAndTraceLog/issues/47

**Comment by openBackhaul** [comment]
Friday call on 12.08.: Attribute shall just be removed from LOADfiles where it is not required.

**Comment by openBackhaul** [comment]
Done.
