### ISSUE TITLE
Bequeath-your-data-and-die needs to return 400 incase of wrong input and not 204

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AdministratorAdministration#76]
Bequeath-your-data-and-die service will process the request ,  if the "application-name" in the request-body matches the "http-server-interface-capability/application-name".
**This functionality is working fine.**
But, incase of wrong "application-name" , the service should return **400 (BAD_REQUEST from client) and not 204**(as its not processing the service)

**Change required :**
server/controllers/individualServices.js need to include response code "responseCodeEnum.code.BAD_REQUEST;" to support sending this response incase of unacceptable application-name.

**Comment by ManasaBM1** [comment]
invalid issue
