### ISSUE TITLE
Use new ConfigurationInput and LogicalTerminationPointServices

### ISSUE THREAD

**Issue by MartinSunal** [openBackhaul/AdministratorAdministration#82]
Create a mapping file for individual services used in this application and use new classes from ApplicationPattern with it.

Application Pattern [#284](https://github.com/openBackhaul/ApplicationPattern/issues/284) [#346](https://github.com/openBackhaul/ApplicationPattern/issues/346)

**Comment by openBackhaul** [comment]
Still valid?

**Comment by PrathibaJee** [comment]
yes , for creating operationClient UUIDs , we are using a mapping file that provides the APISegment and sequence number as specified in the requirement. So , keeping it open and moving it under the v2.0.0_impl milestone. Thanks.

**Comment by DanaSunal** [comment]
Fixed with #145
